# Generated by Django 3.2.3 on 2021-05-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubDate', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('title', models.TextField(help_text='Title', max_length=100)),
                ('content', models.TextField(help_text='Content', max_length=1000)),
                ('signature', models.CharField(help_text='Signature', max_length=100)),
            ],
        ),
    ]
